#!/bin/bash

### BEGIN INIT INFO
# Provides:          wpupdate
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: WPUpdate - Automatic updates for Wordpress.
# Description:       This is an automatic update script for Wordpress
#
### END INIT INFO
# wpupdate
# description: wpupdate
# processname: wpupdate

DAEMON_PATH="/usr/share/wpupdate"

DAEMON=/usr/share/wpupdate/wpupdate.py
DAEMONOPTS=""

NAME=wpupdate
DESC="WPUpdate - automatically update wordpress"
PIDFILE=/var/run/wpupdate.pid
SCRIPTNAME=/etc/init.d/wpupdate

case "$1" in
start)
    printf "%-50s" "Starting WPUpdate..."
    cd $DAEMON_PATH
    PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
    #echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking WPUpdate..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping WPUpdate..."
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
    $0 stop
    $0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
